# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.3"

default_platform :ios


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "build for testing"
  lane :buildTesting do

    #keychain_name = "ios-build"

    #create_keychain(
      #name: keychain_name,
    #  default_keychain: true,
      #unlock: true,
      #timeout: 3600,
      #lock_when_sleeps: true,
      #password: SecureRandom.base64
  #  )

  # Import distribution certificate
    #import_certificate(
      #certificate_path: "/Users/hchukwuji/Documents/workspace/ios-projects/xcuitest-github/xctest-xcuitest-project/scripts/certs/dist-key.p1",
      #certificate_password: ENV["KEY_PASSWORD"],
      #keychain_name: keychain_name
    #)

    # Fetch provisioning profile
    #sigh(
      #adhoc: true,
      #username: "hilary.chukwuji@zalando.de",
      #team_id: "J67E9B6234",
      #provisioning_name: "Calculator Distribution",
      #cert_id: "HXU8W7567B"
    #)

    xcodebuild(
      clean: true,
      derivedDataPath: "project/app",
      scheme: 'calculator',
      destination: 'generic/platform=iOS',
      configuration: 'Development',
      xcargs: " build-for-testing")
      #'xcargs: "build")
      sh 'echo "creating .ipa file this may take some minutes"'
      _script_ipa = "/Users/hchukwuji/Documents/workspace/ios-projects/xcuitest-github/xctest-xcuitest-project/scripts/zip_to_ipa.sh"
      system("sh #{_script_ipa}")
      sh 'echo "launching XCUITest on the Testdroid Cloud"'
      _script_launch_xcuitest = "/Users/hchukwuji/Documents/workspace/ios-projects/xcuitest-github/xctest-xcuitest-project/scripts/launch-xcuitest.sh"
      system("sh #{_script_launch_xcuitest}")

      delete_keychain(
        name: keychain_name
      )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
      clean: true,
      #workspace: "/Users/hchukwuji/Documents/workspace/ios-projects/xcuitest-github/xctest-xcuitest-project/project/calculator.xcodepro",
      output_directory: "app",
      output_name: "calculator.ipa",
      configuration: "Release",
      #output_name: "calculatorUITests-Runner.app",
      scheme: "calculator",
      #build_path: "app/build",
      derived_data_path: "app",
      destination: "generic/platform=iOS",
      xcargs: "build-for-testing"

    )# Build your app - more options available
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
